{
 "title": "qBittorrent",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "All Time Downloaded",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "qbittorrent_global_alltime_downloaded_bytes"
    }
   ]
  },
  {
   "title": "All Time Uploaded",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "qbittorrent_global_alltime_uploaded_bytes"
    }
   ]
  },
  {
   "title": "qBittorrent Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    { "expr": "qbittorrent_app_version", "legendFormat": "{{version}}" }
   ]
  },
  {
   "title": "Total Torrents",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "qbittorrent_global_torrents" }
   ]
  },
  {
   "title": "Global Ratio",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "qbittorrent_global_ratio" }
   ]
  },
  {
   "title": "Global Download Speed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "qbittorrent_global_download_speed_bytes"
    }
   ]
  },
  {
   "title": "States",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "qbittorrent_torrent_states", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Torrents",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    { "expr": "qbittorrent_torrent_info" }
   ]
  },
  {
   "title": "Cumulative Download/Upload Speed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "qbittorrent_global_download_speed_bytes",
     "legendFormat": "Download"
    },
    {
     "expr": "qbittorrent_global_upload_speed_bytes",
     "legendFormat": "Upload"
    }
   ]
  },
  {
   "title": "Incomplete Torrent Progress",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "qbittorrent_torrent_progress < 1.0",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}