global:
  scrape_interval: 30s
  scrape_timeout: 10s

rule_files:
  - alert.yml

scrape_configs:
  - job_name: qbittorrent
    metrics_path: /metrics
    static_configs:
      - targets: [ 'qbittorrent-exporter:17871', 'node-exporter:9100' ]